names:
- Mask
- can
- cellphone
- electronics
- gbottle
- glove
- metal
- misc
- net
- pbag
- pbottle
- plastic
- rod
- sunglasses
- tire
nc: 15
path: /kaggle/input/water-data
test: ./test/images
train: ./train/images
val: ./valid/images
